services:
  frontend:
    build: ./frontend/.
    ports:
      - "8080:3001"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - my-network

  backend:
    build: ./backend/.
    ports:
      - "8081:8080"
    networks:
      - my-network

    volumes:
      - ./backend/src:/app/src

networks:
  my-network: