# Use official Maven image with OpenJDK
FROM maven:3.9.6-eclipse-temurin-21

# Set working directory
WORKDIR /app
COPY pom.xml .

# VOLUME ["/app/data", "/app/src"]

# Run Maven build
RUN mvn dependency:resolve

# Expose ports (if needed for networking)
EXPOSE 8080

# CMD ["mvn", "spring-boot:run"]
# Keep the container running
CMD ["tail", "-f", "/dev/null"]